#!/usr/bin/env python3
"""
generate_pc_header.py
---------------------
Reads a VulkanSC pipeline-cache binary and writes a C++ header file that
embeds the data as a constexpr byte array.

Usage:
    python generate_pc_header.py <input.bin> <output.hpp>

The generated header defines:
    namespace sim {
        static constexpr uint8_t  kPipelineCacheData[N] = { 0x.., ... };
        static constexpr uint32_t kPipelineCacheDataSize = N;
    }
"""

import sys
import os


def main() -> int:
    if len(sys.argv) != 3:
        print("Usage: generate_pc_header.py <input.bin> <output.hpp>",
              file=sys.stderr)
        return 1

    in_path  = sys.argv[1]
    out_path = sys.argv[2]

    if not os.path.isfile(in_path):
        print(f"ERROR: input file not found: {in_path}", file=sys.stderr)
        return 1

    with open(in_path, "rb") as f:
        data = f.read()

    size = len(data)

    # Build hex byte list, 12 bytes per line for readability.
    hex_chunks = []
    for i, byte in enumerate(data):
        if i % 12 == 0:
            hex_chunks.append("\n    ")
        hex_chunks.append(f"0x{byte:02X}U,")

    hex_body = "".join(hex_chunks).rstrip(",")

    header = (
        "/// @file pipeline_cache_data.hpp\n"
        "/// @brief Auto-generated pipeline cache binary embedded as a C++ array.\n"
        "///\n"
        "/// DO NOT EDIT -- regenerated by tools/generate_pc_header.py\n"
        "///\n"
        "/// Contains both horizon_bg and horizon_line pre-compiled pipelines.\n"
        "\n"
        "#ifndef VKSC_SIM_RENDERING_PIPELINE_CACHE_DATA_HPP\n"
        "#define VKSC_SIM_RENDERING_PIPELINE_CACHE_DATA_HPP\n"
        "\n"
        "#include <cstdint>\n"
        "\n"
        "namespace sim {\n"
        "\n"
        f"static constexpr uint32_t kPipelineCacheDataSize{{static_cast<uint32_t>({size}U)}};\n"
        "\n"
        "// NOLINTNEXTLINE(cppcoreguidelines-avoid-c-arrays,modernize-avoid-c-arrays)\n"
        f"static constexpr uint8_t kPipelineCacheData[{size}U] = {{"
        f"{hex_body}\n"
        "};\n"
        "\n"
        "} /* namespace sim */\n"
        "\n"
        "#endif /* VKSC_SIM_RENDERING_PIPELINE_CACHE_DATA_HPP */\n"
    )

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header)

    print(f"[generate_pc_header] Written {size} bytes to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
